import os  # Provides access to operating-system environment variables.
import sqlite3  # Provides SQLite database access for the original local database.
import psycopg  # Provides PostgreSQL database access.
from psycopg import sql  # Provides safe SQL construction for table and column identifiers.

SQLITE_DB = "hardware_inventory.db"  # Stores the filename of the original SQLite database.
DATABASE_URL = os.getenv("DATABASE_URL")  # Reads the PostgreSQL connection string from the environment.

if not DATABASE_URL:  # Checks whether the PostgreSQL connection string was provided.
    raise RuntimeError("DATABASE_URL is not set.")  # Stops the migration if the connection string is missing.

sqlite_conn = sqlite3.connect(SQLITE_DB)  # Opens the original SQLite database.
sqlite_conn.row_factory = sqlite3.Row  # Allows SQLite rows to be accessed by column name.
pg_conn = psycopg.connect(DATABASE_URL)  # Opens a connection to the Supabase PostgreSQL database.
pg_conn.autocommit = False  # Uses a transaction so changes can be rolled back if an error occurs.

try:  # Starts the protected migration section.
    pg_cur = pg_conn.cursor()  # Creates a PostgreSQL cursor for SQL commands.
    sqlite_cur = sqlite_conn.cursor()  # Creates a SQLite cursor for reading source data.

    # 1. KUNIN MUNA ANG TOTOONG SCHEMA MULA SA SQLITE
    def get_sqlite_columns(table_name):
        try:
            sqlite_cur.execute(f"PRAGMA table_info({table_name})")
            return [row[1] for row in sqlite_cur.fetchall()]
        except sqlite3.OperationalError:
            return []

    # 2. BUMUO NG POSTGRESQL TABLES DYNAMICALLY BATAY SA SQLITE COLUMNS
    # Ginagamit ang TEXT / NUMERIC / BIGINT para hindi magka-mismatch ang columns
    table_names = ["users", "password_resets", "hardware", "loans"]
    
    # Drop existing tables cascade para malinis ang failed schema
    for table_name in reversed(table_names):
        pg_cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(sql.Identifier(table_name)))

    counts = {}

    for table_name in table_names:
        cols = get_sqlite_columns(table_name)
        
        if not cols:
            # Kung wala sa SQLite, buuin gamit ang default fallback definitions
            if table_name == "password_resets":
                create_query = """
                CREATE TABLE IF NOT EXISTS password_resets (
                    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT NOT NULL,
                    email TEXT NOT NULL,
                    new_password_hash TEXT NOT NULL,
                    request_time TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'PENDING'
                )
                """
                pg_cur.execute(create_query)
            counts[table_name] = 0
            continue

        # Dynamic table creation batay sa totoong SQLite columns
        column_defs = []
        for col in cols:
            if col in ["id", "item_id", "loan_id", "request_id"]:
                column_defs.append(f"{col} BIGINT PRIMARY KEY")
            else:
                column_defs.append(f"{col} TEXT")
                
        create_sql = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(
            sql.Identifier(table_name),
            sql.SQL(", ").join(sql.SQL(c) for c in column_defs)
        )
        pg_cur.execute(create_sql)

        # READ AND INSERT DATA
        sqlite_cur.execute(f"SELECT * FROM {table_name}")
        rows = sqlite_cur.fetchall()
        counts[table_name] = len(rows)

        if rows:
            source_columns = [description[0] for description in sqlite_cur.description]
            column_identifiers = sql.SQL(", ").join(sql.Identifier(c) for c in source_columns)
            placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in source_columns)
            insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
                sql.Identifier(table_name), column_identifiers, placeholders
            )

            for row in rows:
                values = [row[c] for c in source_columns]
                pg_cur.execute(insert_sql, values)

    # 3. FIX SEQUENCE DYNAMICALLY FOR PRIMARY KEYS
    primary_keys = {"users": "id", "password_resets": "request_id", "hardware": "id", "loans": "loan_id"}
    for table_name, pk in primary_keys.items():
        cols = get_sqlite_columns(table_name)
        if pk in cols or table_name == "password_resets":
            try:
                # Add identity/sequence if missing
                pg_cur.execute(sql.SQL("""
                    ALTER TABLE {} ALTER COLUMN {} ADD GENERATED BY DEFAULT AS IDENTITY;
                """).format(sql.Identifier(table_name), sql.Identifier(pk)))
            except Exception:
                pg_conn.rollback()
                # Re-open cursor if rollback happens on non-critical alter
                pg_cur = pg_conn.cursor()

            seq_sql = sql.SQL(
                "SELECT setval(pg_get_serial_sequence({}, {}), GREATEST(COALESCE(MAX({}), 1), 1), MAX({}) IS NOT NULL) FROM {}"
            ).format(
                sql.Literal(table_name),
                sql.Literal(pk),
                sql.Identifier(pk),
                sql.Identifier(pk),
                sql.Identifier(table_name),
            )
            try:
                pg_cur.execute(seq_sql)
            except Exception:
                pass

    pg_conn.commit()
    print("Migration completed successfully.")
    for t_name in table_names:
        print(f"  {t_name}: {counts.get(t_name, 0)}")

except Exception:
    pg_conn.rollback()
    raise

finally:
    sqlite_conn.close()
    pg_conn.close()